version: '3'
# networks:
#   test-network:
volumes:
  mongodb:
services:
  service:
    depends_on:
      - mongo
      - redis
    container_name: service
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - redis
      - mongo
    # networks:
    #   - test-network
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
    # networks:
    #   - test-network
  redis:
    image: redis:5
    ports:
      - '6379:6379'
    # networks:
    #   - test-network
